project:
  type: website

website:
  title: "Muhammad Abdullahi"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/muhaksim
      - icon: twitter
        href: https://twitter.com/muhaksim
      - icon: linkedin
        href: https://www.linkedin.com/in/muhaksim
  twitter-card: true
  
  
format:
  html:
    theme: cosmo
    css: styles.css



